name: Flutter CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Cài Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          # hoặc fix version:
          # flutter-version: '3.24.5'
          cache: true

      # Lấy dependencies
      - name: Flutter pub get
        run: flutter pub get

      # Phân tích code
      - name: Analyze project source
        run: flutter analyze

      # Chạy test Flutter
      # - name: Run tests
      #   run: flutter test
